# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [9]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [10]:
weather_df = pd.read_csv('weather.csv')
weather_df

,Date,Longitude,Latitude,City,Country,Temperature,% Cloudiness,Wind Speed,% Humidity
0,1637973176,-76.2167,-13.7000,Pisco,PE,66.25,0,13.80,82
1,1637973176,147.0587,-42.7826,New Norfolk,AU,58.50,88,2.51,40
2,1637973177,-102.2000,17.9583,Lázaro Cárdenas,MX,78.44,40,3.47,77
3,1637973177,-133.0374,69.4541,Tuktoyaktuk,CA,-2.20,90,21.85,84
4,1637973177,-70.9167,-53.1500,Punta Arenas,CL,48.31,75,19.57,66
...,...,...,...,...,...,...,...,...,...
574,1637973307,105.2942,27.3125,Bijie,CN,42.66,100,1.25,81
575,1637973458,103.5333,-3.8000,Lahat,ID,76.15,99,1.57,93
576,1637973458,71.7622,21.0914,Mahuva,IN,75.24,93,5.97,46
577,1637973459,-80.5887,28.0345,Palm Bay,US,68.63,90,4.61,68
578,1637973459,-70.1733,1.1983,Mitú,CO,76.82,100,2.46,83

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [11]:
humidity = weather_df["% Humidity"]
locations = weather_df[["Latitude", "Longitude"]]
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [25]:
ideal_weather = weather_df.loc[weather_df['Wind Speed'] < 10]
ideal_weather = ideal_weather.loc[(ideal_weather['Temperature'] > 60) & (ideal_weather['Temperature']< 90)]
ideal_weather = ideal_weather.loc[ideal_weather['% Cloudiness'] < 20]
ideal_weather = ideal_weather.reset_index()
ideal_weather

,index,Date,Longitude,Latitude,City,Country,Temperature,% Cloudiness,Wind Speed,% Humidity
0,31,1637973190,-54.3333,-34.4833,Rocha,UY,62.49,13,6.51,98
1,84,1637973213,147.2712,-2.0226,Lorengau,PG,86.07,13,1.72,64
2,87,1637973214,44.9661,34.6959,Kifrī,IQ,61.88,0,6.82,39
3,89,1637973215,76.4000,21.4667,Nepānagar,IN,65.12,0,1.45,53
4,93,1637973217,46.7219,24.6877,Riyadh,SA,62.74,0,2.62,39
5,120,1637973228,-50.0119,-24.7911,Castro,BR,61.32,0,3.49,84
6,131,1637973233,37.2685,25.0213,Umluj,SA,77.38,10,8.97,45
7,154,1637973243,24.6667,14.2000,Kutum,SD,60.03,5,7.65,21
8,158,1637973205,-99.8901,16.8634,Acapulco de Juárez,MX,78.51,14,4.25,82
9,173,1637973252,21.5482,29.0331,Jalu,LY,64.27,5,7.96,66
10,177,1637973255,46.4667,14.4000,Marzuq,YE,66.29,0,2.73,48
11,195,1637973267,90.8333,22.9500,Lakshmīpur,BD,63.16,2,6.58,61
12,200,1637973270,2.5998,7.3633,Kétou,BJ,76.46,14,2.01,91
13,238,1637973026,55.4033,25.3573,Sharjah city,AE,68.99,0,3.44,78
14,250,1637973290,57.7625,-20.2078,Quatre Cocos,MU,73.51,0,5.93,69
15,251,1637973290,-120.7516,37.1666,Merced,US,63.03,3,4.07,42
16,252,1637973014,-70.7581,-28.5708,Vallenar,CL,64.90,0,4.09,59
17,259,1637973293,54.0924,17.0151,Salalah,OM,73.49,0,3.44,46
18,264,1637973296,-89.8275,13.5928,Acajutla,SV,86.34,16,3.67,62
19,266,1637973297,-42.7263,-10.8218,Xique-Xique,BR,76.41,18,7.05,72
20,275,1637973301,82.6500,27.5167,Pachperwa,IN,60.22,0,3.47,71
21,283,1637973305,8.5167,12.0001,Kano,NG,72.72,10,8.43,14
22,291,1637973309,143.2092,-9.0763,Daru,PG,85.26,19,4.25,71
23,303,1637973314,-115.9500,30.4833,San Quintín,MX,65.97,0,1.45,42
24,326,1637973327,35.3833,-23.8650,Inhambane,MZ,67.64,2,9.75,68
25,327,1637973067,57.6142,-19.9842,Cap Malheureux,MU,73.89,1,9.42,67
26,333,1637973329,-35.2086,-6.0911,Nísia Floresta,BR,82.78,12,8.19,83
27,341,1637973002,-123.2078,39.1502,Ukiah,US,64.29,1,0.00,42
28,344,1637973333,1.0114,20.1986,Tessalit,ML,74.86,10,7.74,32
29,347,1637972988,-156.6825,20.8783,Lahaina,US,82.08,12,6.51,54
30,365,1637973343,-3.0000,9.2667,Bouna,CI,78.82,11,4.34,36
31,377,1637973348,70.9116,29.3846,Alipur,PK,64.58,0,3.38,23
32,379,1637973349,-6.1219,14.7328,Sokolo,ML,81.21,2,9.71,23
33,381,1637973350,34.1333,-5.9500,Mgandu,TZ,63.99,6,5.93,67
34,399,1637973358,34.9500,-5.8500,Kilimatinde,TZ,69.33,11,3.60,62
35,403,1637973359,21.2561,-28.4478,Upington,ZA,68.38,0,8.05,37
36,404,1637973360,-58.5172,-33.0094,Gualeguaychú,AR,68.02,0,8.30,49
37,409,1637973362,80.7167,25.5500,Baberu,IN,60.19,0,4.65,46
38,439,1637973378,-121.4238,38.4210,Laguna,US,61.90,1,5.75,41
39,444,1637973380,74.3833,29.2833,Rāwatsār,IN,62.92,0,7.29,34
40,446,1637973381,-70.6483,-33.4569,Santiago,CL,67.44,0,6.91,59
41,462,1637973394,145.5167,-37.6500,Healesville,AU,64.29,4,6.85,36
42,466,1637973396,-5.0242,5.1367,Grand-Lahou,CI,78.08,16,6.60,88
43,480,1637973404,173.7833,-35.1000,Kaeo,NZ,69.80,5,7.54,54
44,481,1637973404,57.6608,-20.0064,Grand Gaube,MU,73.80,0,9.15,67
45,485,1637973406,12.0333,9.4667,Numan,NG,73.71,13,1.28,22
46,488,1637973407,30.7792,28.4190,Maţāy,EG,63.34,0,5.57,45
47,533,1637973432,-1.7306,8.0563,Kintampo,GH,77.77,15,6.35,54
48,537,1637973435,12.9164,18.6853,Bilma,NE,74.05,6,7.78,17
49,544,1637973439,-0.1436,12.9714,Bogandé,BF,78.93,9,9.10,20

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure